_wandb:
    value:
        cli_version: 0.25.1
        e:
            6rmdmow14fg8shtrkhr68krojhucn1zj:
                codePath: train_and_save_model.py
                codePathLocal: train_and_save_model.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "511027703808"
                        used: "151945162752"
                email: siddhantbhalerao2006@gmail.com
                executable: C:\Users\Siddhani\Desktop\ASEP 2 clude ai\disaster_management_a\.venv\Scripts\python.exe
                git:
                    commit: 2d3b89e919343b4e579673ca05ad495ebb1d888c
                    remote: https://github.com/siddhantbhalerao2006-glitch/disaster_management_ai.git
                gpu: NVIDIA GeForce RTX 2050
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2048
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce RTX 2050
                      uuid: GPU-5041d73f-f729-13ab-49cb-481422e6212c
                host: siddhant
                memory:
                    total: "16390750208"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\Siddhani\Desktop\ASEP 2 clude ai\disaster_management_a\train_and_save_model.py
                python: CPython 3.14.2
                root: C:\Users\Siddhani\Desktop\ASEP 2 clude ai\disaster_management_a
                startedAt: "2026-03-30T08:47:43.583200Z"
                writerId: 6rmdmow14fg8shtrkhr68krojhucn1zj
        m: []
        python_version: 3.14.2
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 16
            "4": 3.14.2
            "5": 0.25.1
            "8":
                - 3
            "12": 0.25.1
            "13": windows-amd64
max_depth:
    value: 10
n_estimators:
    value: 100
test_size:
    value: 0.2
